#!/bin/bash

# Remove output and log directories generated by the pipeline

rm -rf out/cutadapt out/merged out/multiqc out/star

rm -rf log/*.log

rm -f data/*.fastq.gz 

rm -rf res/contaminants.fasta res/contaminants_idx/ res/contaminants.fasta.gz

echo "Pipeline-generated files and directories have been removed."